pipeline {
    agent {
        label 'Jenkins-agent'
    }
    
    stages {
        stage("code") {
            steps {
                git url: "https://github.com/Supu-27/node-todo-cicd-project.git", branch: "master"
                echo "code cloned successfully"
            }
        }
        
        stage("build") {
            steps {
                sh 'docker build -t node-todo-app:latest .'
                echo "code build successfully"
            }
        }
        
        stage("Push to Private Docker Hub Repo") {
            steps {
                withCredentials([usernamePassword(credentialsId:"DockerHubCreds",passwordVariable:"dockerPass", usernameVariable:"dockerUser")]) {
                    sh "docker login -u ${env.dockerUser} -p ${env.dockerPass}"
                    sh "docker tag node-todo-app:latest ${env.dockerUser}/node-todo-app:latest" // Corrected image name
                    sh "docker push ${env.dockerUser}/node-todo-app:latest" // Corrected image name
                    echo "Docker Image Pushed successfully"
                }
            }
        }
        
        stage("deploy") {
            steps {
                sh "docker-compose up -d" // Make sure docker-compose is installed and config is correct
                echo "Node-app deployed successfully"
            }
        }
    }
}
